module3 done
indubidably/Py4TA pull request #3
Opened 2023-09-26 10:50 UTC by indubidably

2023-09-26 16:06 UTC, alpakhomov requested changes
Left a bunch of comments; pls fix your solution

2023-09-26 16:06 UTC, alpakhomov commented on Homeworks/module3/hw1.py
> +    if len(arr) == 5:
You can just `return len(arr) == 5` right away; it's a boolean value

2023-09-26 16:06 UTC, alpakhomov commented on Homeworks/module3/hw1.py
> +    if re.match(r'\d{4}-\d{2}-\d{2}\n', core):
Here you can cast result of regex to bool value and just return it; no if/else needed `return bool(re.match(...))`

2023-09-26 16:06 UTC, alpakhomov commented on Homeworks/module3/hw1.py
> +    res = open("result.txt", "w")
You are not closing both of your files; pls use context manager, so that python will close it for you

2023-09-26 16:06 UTC, alpakhomov commented on Homeworks/module3/hw1.py
> +    return os.getcwd()+"\\result.txt"
This doesn't work on macos/linux; backwards slash symbol exists as path separator only on windows. Please use `abspath` function from os module - it will just return absolute path for current os

2023-09-26 16:06 UTC, alpakhomov commented on Homeworks/module3/hw1.py
> +        if not (validate_line(x)):
You are not using `validators` iterable. There can be more than 2 validators. You should iterate over `validators`; each element of this collection will be a function - you should check if it returns true. If not - write the line to a report file. You can get validator name with `validator.__name__`

2023-09-26 16:06 UTC, alpakhomov commented on Homeworks/module3/hw3.py
> +        return output
It works, but you can simplify it quite a bit - try just figuring out all necessary arguments; and just `return list(your_iterable[start:stop:step])`

2023-09-27 14:39 UTC, alpakhomov approved these changes
Approved!

2023-09-27 17:26 UTC, MChislov approved these changes

2023-09-28 12:08 UTC, merged