module6 done
indubidably/Py4TA pull request #6
Opened 2023-10-05 10:58 UTC by indubidably

2023-10-10 18:27 UTC, leo-ri approved these changes
Approve

2023-10-10 20:09 UTC, AnastasiiaGor requested changes

2023-10-10 20:09 UTC, AnastasiiaGor commented on Homeworks/module6/hw_ig.py
> +        elif isinstance(elem, (list, tuple)):
There might be other iterable types here
`hasattr(elem, '__iter__')` may help

2023-10-10 20:09 UTC, AnastasiiaGor commented on Homeworks/module6/hw_ig.py
> +            for item in elem:
`yield from merge_elems(*elem)` would work also

2023-10-11 15:20 UTC, AnastasiiaGor approved these changes

2023-10-12 12:10 UTC, merged